project_id = "uxekjczwztspjbhdgtxy"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.self-signup]
verify_jwt = false

[functions.reset-dealer-password]
verify_jwt = false

[functions.onboard-dealer]
verify_jwt = false

[functions.dealer-ai-chat]
verify_jwt = false
